# Generated by Django 4.0.4 on 2022-07-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_likes_profile_i_like_profile_likes_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='i_like',
            new_name='liked_mangoes',
        ),
    ]
