# Generated by Django 4.0.4 on 2022-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_profile_picture',
            field=models.BooleanField(default=False),
        ),
    ]
