# Generated by Django 4.0.4 on 2022-07-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_chat_to_alter_chat_user_alter_reply_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='reply',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
