# Generated by Django 4.0.4 on 2022-07-12 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_chat_message_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
